import { useIntlDisplayNames } from "@mkboard/intl";
import { Language } from "@mkboard/keyboard";
import { Alphabet, Filter, type PhoneticModel } from "@mkboard/phonetic-model";
import { PhoneticModelLoader } from "@mkboard/phonetic-model-loader";
import { useSettings } from "@mkboard/settings";
import { Field, FieldList, FieldSet, OptionList, Para } from "@mkboard/widget";
import { useIntl } from "react-intl";
import { typingTestProps } from "../../../settings.ts";

export function PseudoWordsSettings() {
  const { settings } = useSettings();
  return (
    <PhoneticModelLoader language={settings.get(typingTestProps.language)}>
      {(model) => <Content model={model} />}
    </PhoneticModelLoader>
  );
}

function Content({ model }: { model: PhoneticModel }) {
  const { settings, updateSettings } = useSettings();
  const { formatMessage } = useIntl();
  const { formatLanguageName } = useIntlDisplayNames();
  const words = [];
  for (let i = 0; i < 50; i++) {
    words.push(model.nextWord(Filter.empty));
  }
  return (
    <FieldSet legend="Pseudo words">
      <Para>
        Type pseudo words generated by an algorithm according to the phonetic
        rules of your language.
      </Para>

      <FieldList>
        <Field>
          {formatMessage({
            id: "t_Language:",
            defaultMessage: "Language:",
          })}
        </Field>

        <Field>
          <OptionList
            options={Language.ALL.map((item) => ({
              value: item.id,
              name: formatLanguageName(item.id),
            }))}
            value={String(settings.get(typingTestProps.language))}
            onSelect={(id) => {
              updateSettings(
                settings.set(typingTestProps.language, Language.ALL.get(id)),
              );
            }}
          />
        </Field>
      </FieldList>

      <FieldList>
        <Field>Alphabet:</Field>
        <Field>
          <Alphabet model={model} />
        </Field>
      </FieldList>

      <FieldList>
        <Field>Example:</Field>
        <Field>
          <em>{words.join(" ")}</em>
        </Field>
      </FieldList>
    </FieldSet>
  );
}
